name: Docker Image CI

on:
    push:
        branches: ["master"]
    workflow_dispatch:

env:
    REGISTRY: "ghcr.io"
    IMAGE: "lets-go-gambling"

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write

        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to Docker registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      ${{ env.REGISTRY }}/mrtalon63/${{ env.IMAGE }}:latest
                      ${{ env.REGISTRY }}/mrtalon63/${{ env.IMAGE }}:${{ github.RUN_ID }}
